
export const defaultTheme = {
    colors: {
        "white": "#fff",
        "black": "#1c1c1c",
        "gray": "#333",
        "base-input": "#EDEDED",
        "base-button": "#E6E5E5",
        "base-hover": "#D7D5D5",
        "base-label": "#8D8686",
        "base-text": "#574F4D",
        "base-title": "#272221",
        "base-error": "#f84747",
        "nude": "#e6c1a2",  
        "bege": "#d4a481",  
        "rose": "#f2e8e4",
        "page": "#f9f6f2",
        "darkGray": "#2f2f2f",
        "lightGray": "#d9d9d9",
    },
    textSizes: {
        "title-title-xl": "3rem",
        "title-title-l": "2rem",
        "title-title-m": "1.5rem",
        "title-title-s": "1.2rem",
        "title-title-xs": "1.125rem",
        "text-regular-l": "1.25rem",
        "text-bold-l": "1.25rem",
        "text-regular-m": "1rem",
        "text-bold-m": "1rem",
        "text-regular-s": "0.875rem",
        "text-bold-s": "0.75rem",
        "components-tag": "0.625rem",
        "components-button-g": "0.875rem",
        "components-button-s": "0.75rem",
    },
    fonts: {
        regular: "'Roboto', sans-serif",
        intro: "'Montserrat', serif",
    },
}
